name: 'Coverage Ratchet'
description: 'Flag if pull requests that would reduce code coverage'
inputs:
  working_directory:
    description: 'directory with coverage folder'
    required: true
  coverage_summary_path:
    description: 'path inside working_directory to coverage summary json'
    default: 'coverage/coverage-summary.json'
    required: false
  test_script:
    description: 'script to generate coverage report (ex: npm run test)'
    required: true
  github_token:
    description: 'A github access token'
    required: true
    default: ${{ github.token }}
  default_branch:
    description: 'Default branch name (typically "main" or "master")'
    required: false
    default: ${{ github.event.repository.default_branch }}
  margin:
    description: 'Only report failure if decline is larger than this margin'
    required: false
    default: 0
outputs:
  declines:
    description: 'declining coverage output'
runs:
  using: 'node16'
  main: 'dist/index.js'
